# Spring configuration
spring:
   application:
      name: mysite06
   # devtools - live reload      
   devtools:
      livereload:
         enabled: ture
   # mvc
   mvc:
      static-path-pattern: /assets/**
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   web:
      resources:
         static-location: classpath:/assets/, file:/Users/awlals/Documents/douzone2023/eclipse/eclipse-workspace/mysite/mysite-uploads/
   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB
   #message resources(internationalization, i18n)
   messages:
      always-message-format: true
      basename: web/messages_ko, web/messages_en
      encoding: utf-8
   # EnableAspectJAutoProxy
   aop:
      auto: true
      proxytarget-class: true
      
         
# server
server:
   port: 9090